[part1-example1_p1]
interpreter = "pypy311"
code = "ec202420.py"
input_path = "example1_p1.txt"
value = 1_045
solved = true
duration = 0.015054628000143566

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202420.py"
input_path = "example1_p2.txt"
value = 24
solved = true
duration = 0.14325952400031383

[part2-example2_p2]
interpreter = "pypy311"
code = "ec202420.py"
input_path = "example2_p2.txt"
value = 78
solved = true
duration = 3.65295535399855

[part2-example3_p2]
interpreter = "pypy311"
code = "ec202420.py"
input_path = "example3_p2.txt"
value = 206
solved = true
duration = 4.520843770000283

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202420.py"
input_path = "example1_p3.txt"
value = 768_791
solved = true
duration = 0.000547698000445962
