[part1-example1_p1]
interpreter = "pypy311"
code = "ec202515.py"
input_path = "example1_p1.txt"
value = 8
solved = true
duration = 0.00029540200011979323

[part1-example2_p1]
interpreter = "pypy311"
code = "ec202515.py"
input_path = "example2_p1.txt"
value = 16
solved = true
duration = 0.0010256690002279356

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202515.py"
input_path = "example1_p3.txt"
value = 2_038
solved = true
duration = 0.0022830670004623244
