[part1-example1_p1]
interpreter = "pypy311"
code = "ec202520.py"
input_path = "example1_p1.txt"
value = 7
solved = true
duration = 9.955200948752463e-05

[part1-example2_p1]
interpreter = "pypy311"
code = "ec202520.py"
input_path = "example2_p1.txt"
value = 0
solved = true
duration = 9.661298827268183e-05

[part1-example3_p1]
interpreter = "pypy311"
code = "ec202520.py"
input_path = "example3_p1.txt"
value = 0
solved = true
duration = 7.193099008873105e-05

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202520.py"
input_path = "example1_p2.txt"
value = 32
solved = true
duration = 0.0007145409908844158

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202520.py"
input_path = "example1_p3.txt"
value = 23
solved = true
duration = 0.000795260988525115

[part3-example2_p3]
interpreter = "pypy311"
code = "ec202520.py"
input_path = "example2_p3.txt"
value = 23
solved = true
duration = 0.0010177490039495751
