[part1-example1_p1]
interpreter = "pypy311"
code = "ec202519.py"
input_path = "example1_p1.txt"
value = 24
solved = true
duration = 8.610700024291873e-05

[part1-example2_p1]
interpreter = "pypy311"
code = "ec202519.py"
input_path = "example2_p1.txt"
value = 11
solved = true
duration = 0.0001552800094941631

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202519.py"
input_path = "example1_p2.txt"
value = 22
solved = true
duration = 0.00011704000644385815
