[part1-example1_p1]
interpreter = "pypy311"
code = "ec202517.py"
input_path = "example1_p1.txt"
value = 1_573
solved = true
duration = 0.0011472260011942126

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202517.py"
input_path = "example1_p2.txt"
value = 1_090
solved = true
duration = 0.0027321749948896468

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202517.py"
input_path = "example1_p3.txt"
value = 592
solved = true
duration = 0.027792214998044074

[part3-example2_p3]
interpreter = "pypy311"
code = "ec202517.py"
input_path = "example2_p3.txt"
value = 330
solved = true
duration = 0.016271808999590576

[part3-example3_p3]
interpreter = "pypy311"
code = "ec202517.py"
input_path = "example3_p3.txt"
value = 3_180
solved = true
duration = 0.033367545998771675
