[part1-example_p1]
interpreter = "pypy311"
code = "ec202408.py"
input_path = "example_p1.txt"
value = 21
solved = true
duration = 7.655000445083715e-06

[part2-example_p2]
interpreter = "pypy311"
code = "ec202408.py"
input_path = "example_p2.txt"
value = 19_342_085
solved = true
duration = 3.881900011037942e-05

[part3-example_p3]
interpreter = "pypy311"
code = "ec202408.py"
input_path = "example_p3.txt"
value = 41_067
solved = true
duration = 0.02189907400043012
