[part1-example1_p1]
interpreter = "pypy311"
code = "ec202401.py"
input_path = "example1_p1.txt"
value = 5
solved = true
duration = 5.210000017541461e-05

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202401.py"
input_path = "example1_p2.txt"
value = 28
solved = true
duration = 7.510100022045663e-05

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202401.py"
input_path = "example1_p3.txt"
value = 30
solved = true
duration = 6.915600079082651e-05
