[part1-example1_p1]
interpreter = "pypy311"
code = "ec202503.py"
input_path = "example1_p1.txt"
value = 29
solved = true
duration = 2.2530000023834873e-05

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202503.py"
input_path = "example1_p2.txt"
value = 781
solved = true
duration = 4.787500074598938e-05

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202503.py"
input_path = "example1_p3.txt"
value = 3
solved = true
duration = 7.465099952241872e-05
