[part1-example_p1]
interpreter = "pypy311"
code = "ec202413.py"
input_path = "example_p1.txt"
value = 28
solved = true
duration = 0.00015404800069518387

[part2-example_p2]
interpreter = "pypy311"
code = "ec202413.py"
input_path = "example_p2.txt"
value = 28
solved = true
duration = 0.0001677999971434474

[part3-example_p3]
interpreter = "pypy311"
code = "ec202413.py"
input_path = "example_p3.txt"
value = 14
solved = true
duration = 0.0014682719993288629
