[challenge]
name = "Everybody Codes"
url = "https://everybody.codes/"
icon = "ü¶Ü"

[patterns]
solve = "ec*{suffix}.py"
viz = "ecviz*.py"
input = "everybody_codes*{suffix}.txt"
example = "example*{suffix}.txt"
suffixes = ["_p1", "_p2", "_p3"]

[code]
solve_functions = ["part1", "part2", "part3"]

[template]
file_name = "ec{event:03d}{puzzle:02d}.py"
docstring = "Everybody Codes quest {puzzle}, {event}: {name}."

[template.readme]
challenge = "{root_dir}/README.template"
language = "{root_dir}/README.language.template"
event = "{root_dir}/README.event.template"

[languages.python]
language_dir = "{root_dir}/python/src"
icon = "üêç"

[languages.elixir]
language_dir = "{root_dir}/elixir/lib"
icon = "üíß"
