[part1-example1_p1]
interpreter = "pypy311"
code = "ec202507.py"
input_path = "example1_p1.txt"
value = "Oroneth"
solved = true
duration = 3.046700294362381e-05

[part2-example1_p2]
interpreter = "pypy311"
code = "ec202507.py"
input_path = "example1_p2.txt"
value = 23
solved = true
duration = 0.00010139100049855188

[part3-example1_p3]
interpreter = "pypy311"
code = "ec202507.py"
input_path = "example1_p3.txt"
value = 25
solved = true
duration = 9.837999823503196e-05

[part3-example2_p3]
interpreter = "pypy311"
code = "ec202507.py"
input_path = "example2_p3.txt"
value = 1_154
solved = true
duration = 0.011238438004511409
