[part1-example_p1]
interpreter = "pypy311"
code = "ec202417.py"
input_path = "example_p1.txt"
value = 16
solved = true
duration = 5.2830990171059966e-05

[part2-example_p2]
interpreter = "pypy311"
code = "ec202417.py"
input_path = "example_p2.txt"
value = 16
solved = true
duration = 6.245900294743478e-05

[part3-example_p3]
interpreter = "pypy311"
code = "ec202417.py"
input_path = "example_p3.txt"
value = 15_624
solved = true
duration = 0.0005851509922649711
